안녕하세요. 수강생 여러분~! Chapter21 ~ 32 수업은 잘 들으셨나요?

Chapter21 ~ 32의 수업 내용을 바탕으로 아래 문제를 풀어주시면 됩니다.


<br>


[**답변 입력 방법**]

문제 아래에 있는 코드 입력창에 정답코드를 작성하신 후  __▷ 버튼을 클릭해 코드를 실행__ 해보세요<br>

---

[문제 1]
사용자로부터 이름과 나이를 입력 받아, "안녕하세요, [이름]님! 당신은 [나이]살입니다."라고 출력하는 함수 greet_user를 작성하세요.

In [ ]:
def greet_user(name, age):
    print(f"안녕하세요, {name}님! 당신은 {age}살입니다.")

greet_user("김동석", 27)

안녕하세요, 김동석님! 당신은 27살입니다.

---

[문제 2] 여러 숫자를 입력받아 그 합계를 반환하는 함수 sum_numbers를 작성하세요. 이 때, 가변 매개변수를 사용하세요.

In [ ]:
def sum_numbers(*input_numbers):
    total = 0
    for num in input_numbers:
        total += num
    return total

result = sum_numbers(1, 10, 100, 1000)
print(result)

1111

---

[문제 3] 사용자의 이름을 출력하는 함수 print_name을 작성하세요. 만약 이름이 주어지지 않았다면, 기본값으로 "익명"을 사용하세요.

In [ ]:
def print_name(name="익명"):
    print(f"사용자의 이름은 {name}입니다.")

print_name()
print_name("김동석")

사용자의 이름은 익명입니다.
사용자의 이름은 김동석입니다.

---

[문제 4] 사용자의 이름, 나이, 성별을 출력하는 함수 print_info를 작성하세요. 이 때, 모든 매개변수는 키워드 매개변수로만 받도록 하세요.

In [ ]:
def print_info(name, age, gender):
    print(f"이름: {name}, 나이: {age}, 성별: {gender}")

print_info(name="김동석", age=27, gender="남자")

이름: 김동석, 나이: 27, 성별: 남자

---

[문제 5] 두 개의 정수를 받아 합을 반환하는 함수 add를 작성하세요. 매개변수와 반환값에 타입 어노테이션을 추가하세요.

In [ ]:
def add(num1: int, num2: int) -> int:
    return num1 + num2

result = add(33, 66)
print(result)

99

---

[문제 6] 0부터 시작하여 n까지의 숫자 중에서 홀수만 생성하는 제너레이터 odd_numbers를 작성하세요.

In [ ]:
def odd_numbers(n):
    for i in range(n+1):
        if i % 2 == 1:
            yield i


# for 루프를 사용하여 전체 순회
for num in odd_numbers(10):
    print(num)

<generator object odd_numbers at 0x7fe6bf1ab1d0>
1
3
5
7
9

---

[문제 7] 두 숫자를 더하는 람다 함수를 작성하고, 이를 변수에 할당한 후 사용하세요.

In [ ]:
def func_lambda(num1, num2):
    return num1+num2

added_num = func_lambda(10, 20)
print(added_num)

30

---

[문제 8] 사용자로부터 3개의 숫자를 입력받아, 이를 튜플로 만든 후 최소값과 최대값을 출력하는 함수 min_max를 작성하세요.

In [ ]:
def min_max():
    numbers = []

    # 사용자로부터 3개의 숫자 입력받아 리스트로 저장
    for i in range(3):
        num = int(input(f"{i+1}번째 숫자를 입력하세요: "))
        numbers.append(num)

    # 리스트를 튜플로 변환
    numbers_tuple = tuple(numbers)

    min_value = min(numbers_tuple)
    max_value = max(numbers_tuple)

    # 결과 출력
    print("\n----------------------------------")
    print(f"입력된 숫자: {numbers_tuple}")
    print(f"최소값: {min_value}")
    print(f"최대값: {max_value}")
    print("----------------------------------")

# 함수 실행
min_max()

1번째 숫자를 입력하세요: 10
2번째 숫자를 입력하세요: 15
3번째 숫자를 입력하세요: 20

----------------------------------
입력된 숫자 튜플: (10, 15, 20)
최소값: 10
최대값: 20
----------------------------------

---

[문제 9] 주어진 숫자가 짝수인지 확인하는 함수 is_even을 작성하세요. 짝수라면 True를, 아니라면 False를 반환하세요. 함수 내에서 조기 리턴을 활용하세요.

In [ ]:
def is_even(num):
    if num % 2 == 0:
        return True
    else:
        return False

result = is_even(11)
print(result)

False

---

[문제 10] 팩토리얼을 계산하는 재귀 함수 factorial을 작성하세요.

In [ ]:
def factorial(n):
    facto_num = 1
    for i in range(1,n+1):
        facto_num *= i
    return facto_num

result = factorial(5)
print(result)

120

---

[문제 11] 문자열 리스트를 받아, 각 문자열의 길이를 출력하는 함수 print_lengths를 작성하세요.

In [ ]:
def print_lengths(str_lists):
    for str in str_lists:
        print(f"{str}: {len(str)}")

backend_stacks= [
                "Linux",
                "Git",
                "Python",
                ]

print_lengths(backend_stacks)

Linux: 5
Git: 3
Python: 6

---

[문제 12] 두 문자열을 받아서 긴 문자열을 반환하는 함수 longer_string을 작성하세요. 만약 두 문자열의 길이가 같다면, 첫 번째 문자열을 반환하세요.

In [ ]:
def longer_string(str1, str2):
    if len(str1) > len(str2):
        return str1
    elif len(str1) < len(str2):
        return str2
    else:
        return str1

str1 = "Helloooo"
str2 = "World"
result = longer_string(str1, str2)
print(result)

Helloooo