안녕하세요. 수강생 여러분~! Chapter14 ~ 16 수업은 잘 들으셨나요?

Chapter14 ~ 16의 수업 내용을 바탕으로 아래 문제를 풀어주시면 됩니다.

<br>


[**답변 입력 방법**]

문제 아래에 있는 코드 입력창에 정답코드를 작성하신 후  __▷ 버튼을 클릭해 코드를 실행__ 해보세요<br>

---

__[문제1]__

주어진 정수 x와 자연수 n을 이용해, x부터 시작해 x씩 증가하는 숫자를 n개 지니는 리스트를 출력해주세요   
<br>

x = 2, n =5

In [3]:
x = 2
n = 5
result = []

for i in range(1,n+1):
    result.append(i*x)

print(result)

[2, 4, 6, 8, 10]

---

__[문제2]__

전화번호가 문자열 phone_number로 주어졌을 때, 전화번호의 뒷 4자리를 *으로 가린 문자열이 출력되도록 코드를 작성해주세요

phone_number = "01012347890"  
<br>

출력 예) "0101234****"

In [18]:
phone_number = "01012347890"
scrit_number = phone_number[:-4] + "****"
print(scrit_number)

0101234****

---

__[문제3]__

숫자를 건넬 때 일부 자릿수를 영단어로 바꾼 카드를 건네주면 프로도는 원래 숫자를 찾는 게임입니다.

다음은 숫자의 일부 자릿수를 영단어로 바꾸는 예시입니다.

1478 → "one4seveneight"  
234567 → "23four5six7"  
10203 → "1zerotwozero3"    

이렇게 숫자의 일부 자릿수가 영단어로 바뀌어졌거나,   
혹은 바뀌지 않고 그대로인 문자열 s가 주어졌을때
s가 의미하는 원래 숫자를 출력하도록 코드를 작성해주세요

s = "77three4one

---
참고로 각 숫자에 대응되는 영단어는 다음 표와 같습니다.

숫자	영단어  
0	zero  
1	one  
2	two  
3	three  
4	four  
5	five  
6	six  
7	seven  
8	eight  
9	nine

In [20]:
num_mapping = {
    "zero": "0",
    "one": "1",
    "two": "2",
    "three": "3",
    "four": "4",
    "five": "5",
    "six": "6",
    "seven": "7",
    "eight": "8",
    "nine": "9"
}

s = "77three4one"
result = s

for word, digit in num_mapping.items():
    # 문자열.replace(찾을 문자열, 바꿀 문자열)
    result = result.replace(word, digit)

print(f"변환 전: {s}")
print(f"변환 후: {result}")

변환 전: 77three4one
변환 후: 77341

---

__[문제4]__

행렬의 덧셈은 행과 열의 크기가 같은 두 행렬의 같은 행, 같은 열의 값을 서로 더한 결과가 됩니다.

 행렬 arr1과 arr2가 주어졌을 때, 행렬 덧셈의 결과를 출력하는 코드를 작성해주세요(result와 같은 결과가 출력되도록 작성)

arr1 = [[1,2],[2,3]]

arr2 = [[3,4],[5,6]]

result = [[4,6],[7,9]]

In [25]:
arr1 = [[1,2],[2,3]]
arr2 = [[3,4],[5,6]]

rows = len(arr1)    # 행의 개수
cols = len(arr1[0]) # 열의 개수

result = []
for r in range(rows):
    row = []
    for c in range(cols):
        row.append(arr1[r][c] + arr2[r][c])
    result.append(row)

print(result)

[[4, 6], [7, 9]]
[1, 2]

---

__[문제5]__

양의 정수 x가 하샤드 수이려면 x의 자릿수의 합으로 x가 나누어져야 합니다.   
예를 들어 18의 자릿수 합은 1+8=9이고, 18은 9로 나누어 떨어지므로 18은 하샤드 수입니다.   
주어진 x를 이용해 x가 하샤드 수인지 아닌지 검사하는 코드를 작성해주세요

x = 17

----

입출력 예시
x	결과값  
10	true  
12	true  
11	false  
13	false

In [28]:
x = int(input("하샤드 수인지 검사할 숫자: "))

tens_digit = x // 10
ones_digit = x % 10

if (x % (tens_digit + ones_digit)) == 0:
    print(f"{x}는 하샤드 수입니다.")
else:
    print(f"{x}는 하샤드 수가 아닙니다.")

하샤드 수인지 검사할 숫자: 17
17는 하샤드 수가 아닙니다.

---

__[문제6]__

String형 배열 seoul의 element중 "Kim"의 인덱스 x를 찾아, "김서방은 x에 있다"는 String을 출력하는 코드를 작성해주세요.   

seoul에 "Kim"은 오직 한 번만 나타나며 잘못된 값이 입력되는 경우는 없습니다.

seoul = ["Jane", "Kim"]

<br>
출력 예) "김서방은 1에 있다"

In [30]:
seoul = ["Jane", "Kim"]
x = seoul.index("Kim")

print(f"김서방은 {x}에 있다")

김서방은 1에 있다

---

__[문제7]__

0부터 9까지의 숫자 중 일부가 들어있는 정수 배열 numbers가 주어집니다.   
numbers에서 찾을 수 없는 0부터 9까지의 숫자를 모두 찾아 더한 수를 출력해주세요

numbers = [5,8,1,0,6,9]

In [33]:
numbers = [5,8,1,0,6,9]
result = 0

for i in range(10):
    if not(i in numbers):
        result += i

print(result)

16